version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pharmacy-pos-db
    environment:
      POSTGRES_USER: pharmacy
      POSTGRES_PASSWORD: pharmacy123
      POSTGRES_DB: pharmacy_pos
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmacy"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pharmacy-pos-redis
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: pharmacy-pos-search
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-masterKeyForDevelopment123}
      MEILI_ENV: development
    ports:
      - "${MEILI_PORT:-7701}:7700"
    volumes:
      - meilisearch_data:/meili_data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: pharmacy-pos-storage
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "${MINIO_API_PORT:-9100}:9000"
      - "${MINIO_CONSOLE_PORT:-9101}:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: pharmacy-pos-prometheus
    ports:
      - "${PROMETHEUS_PORT:-9091}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    container_name: pharmacy-pos-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    ports:
      - "${GRAFANA_PORT:-3002}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  mailhog:
    image: mailhog/mailhog:latest
    container_name: pharmacy-pos-mail
    ports:
      - "${MAILHOG_SMTP_PORT:-1026}:1025"  # SMTP
      - "${MAILHOG_UI_PORT:-8026}:8025"  # Web UI

volumes:
  postgres_data:
  redis_data:
  meilisearch_data:
  minio_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: pharmacy-pos-network